services:
  - type: web
    name: diabetes-classifier
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn diabetes_classifier.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4